### ISSUE TITLE
1.0.1 doesn't work with node 6

### ISSUE THREAD

**Issue by ghost** [hughsk/vinyl-buffer#8]
1.0.1 doesn't seem to be fully compatible with node 6.
Our build script stopped working properly ( no error was thrown ) and the minified file went from 1.3mb to 400kb ( which would've been nice, if it still worked 😅 ).

We had the following in package.json in regards to vinyl.
"vinyl-buffer": "^1.0.0",
"vinyl-source-stream": "^1.1.0"

My guess is that the problem is that vinyl-buffer 1.0.1 uses "vinyl-source-stream: 2.0.0".
If I run the same script using node 8 there are no issues.

**Comment by phated** [comment]
Other than dependency updates, the only change in v1.0.1 over v1.0.0 was removing an extraneous `file.clone()` call.  That wouldn't have changed compatibility in node 6 vs 8.  You have something else going wrong with your use case but I don't have the capacity to be your personal support.  You might want to create a thread on StackOverflow.

Also, `vinyl-buffer` doesn't use `vinyl-source-stream`, they are just often used together.

**Comment by ghost** [comment]
@phated 
I just reverted to using 1.0.0 instead, I just wanted to leave this here if someone else had similar problems.
